/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

using System;
using UnityEngine;
namespace Filterartifact
{
	public class tablemgr
	{
		private static tablemgr m_instance = null;
		public CTblHistoryRecord g_oTblHistoryRecord = new CTblHistoryRecord();
		public tablemgr()
		{
		}

		public static tablemgr Instance
		{
			get
			{
				if (m_instance == null)
				{
					m_instance = new tablemgr();
				}

				return m_instance;
			}
		}
		public static void empty()
		{
			m_instance = null;
		}
		public bool LoadAllTables(string path = "", AssetBundle bundle = null, string language = "zh-Hans")
		{
			if (false == g_oTblHistoryRecord.LoadFromFile(path, bundle, language))
			{
				DebugLog.LogError("Read TblHistoryRecord Tabel Error!");
				return false;

			}
			return true;
		}
	}
}
